### ISSUE TITLE
2 bugs.

### ISSUE THREAD

**Issue by chezedude** [Mac15001900/idlescape-calc#1] opened 2021-01-11 10:03 UTC
1. final failed aug should be giving half xp instead of full xp.
2. purchased item level is not factored in some of the calculations

fix these lines
`for (var i = itemLevel+1; i <= MAX_AUGMENT; i++) {
    avrAugs+= (i-itemLevel)*(cp(i-1, itemLevel))*(1-p(i));
    avrXp+= cp(i-1, itemLevel)*(1-p(i)) * (cXpGain(i-1, itemLevel) + xpGain(i)/2);
}`

**Comment by Mac15001900** [comment] 2021-02-02 18:50
Thanks for the report! I'm glad this tool is still seeing some use.

The first issue should be fixed now. The second one is intended behaviour, so I've added some clarification about what the purchased item level is meant to affect.

**Closed as completed by Mac15001900** 2021-02-02 18:50 UTC
